### ISSUE TITLE
A param to callback url to configure landing url

### ISSUE THREAD

**Issue by husayt** [storyblok/nuxt-auth#7]
Currently callback url is hardcoded to
```
res.redirect(`/?space_id=${space_id}`)
```
[here](https://github.com/storyblok/nuxt-auth/blob/5572f6e64b0d1d7bf3054892a9e73493b76cefd6/lib/router.js#L43)

Can we change this to smth like
```
res.redirect(`${returnUrl}?space_id=${space_id}`)

```
where `returnUrl` is a param passed to function and defaulted to `"/"`

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue! In the latest version ([v1.4.0](https://github.com/storyblok/nuxt-auth/releases/tag/v1.4.0)), we've implemented a new option called `return_url` to configure this return. You can check it in [our documentation](https://github.com/storyblok/nuxt-auth#defining-a-new-entry-point).
